### PR TITLE
fix: reload bug fix

### LINKED ISSUE #74: Bug: Incorrect active tab on refresh
### Describe the bug
After refreshing the page, the menu shows active tab as Dashboard even if the route is at /forms or /submission

### To Reproduce
1. Go to http://localhost:3000/submission
2. Refresh page

### Expected behavior
Active tab should be the same as the active route.

### Screenshots
osp-tab-issue

### Desktop (please complete the following information):
 - OS: Any
 - Browser : Any
 - Version: Any

### PR DESCRIPTION
**Pull request by jeeva2812**
### Description

Keeping the correct tab active while reloading

Fixes #74 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

reloadBug

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

File: src/components/Menubar.js [hunk 1]
```diff
@@ -33,21 +33,21 @@ class Menubar extends Component {
...
-                active={activeItem === 'forms'}
+                active={activeItem === 'forms' || activeItem === '/forms'}
                 onClick={this.handleItemClick}
                 as={Link}
                 to={forms()}
                 > FORMS </Menu.Item>
                 <Menu.Item
                 name='submissions'
-                active={activeItem === 'submissions'}
+                active={activeItem === 'submissions' || activeItem === '/submissions'}
```
Comment (codesankalp) [inline src/components/Menubar.js]:
```suggestion
                active={activeItem === 'submissions' || activeItem === '/submission'}
```
URL contains `submission`.

File: src/components/Menubar.js [hunk 2]
```diff
@@ -33,21 +33,21 @@ class Menubar extends Component {
             <Menu pointing secondary>
                 <Menu.Item
                 name='dashboard'
-                active={activeItem === 'dashboard'}
+                active={activeItem === 'dashboard' || activeItem === '/dashboard'}
```
Comment (codesankalp) [inline src/components/Menubar.js]:
```suggestion
                active={activeItem === 'dashboard' || activeItem === '/dashboard' || activeItem === '/'}
```
On this url http://localhost:3000/, it must show `dashboard` as active tab.

**Review by codesankalp — CHANGES_REQUESTED** [review]
@jeeva2812 I have suggested some changes. Please look into that.

**Review by codesankalp — DISMISSED** [review]

**Review by Rahulm2310 — COMMENTED** [review]
@codesankalp I think submission() under urls.js file should return ``${urlBaseFrontend()}submissions`` and not ``${urlBaseFrontend()}submission``. What say?

File: src/components/Menubar.js [hunk 3]
```diff
@@ -11,7 +11,7 @@ class Menubar extends Component {
     constructor(props) {
         super(props)
         this.state = {
-            activeItem: 'dashboard'
+            activeItem: window.location.pathname
```
Comment (Rahulm2310) [inline src/components/Menubar.js]: I think a more cleaner code could be `activeItem: window.location.pathname.substring(1) || 'dashboard'`. Adding this along with correcting return url from the submission() function would work. Any other changes will not be needed this way.

Comment (jeeva2812) [reply src/components/Menubar.js]: This might not work as window.location.pathname returns string without slash during internal navigation. 
What about `window.location.pathname[0] == '/' ? window.location.pathname.substr(1) : window.location.pathname;`

**Comment by codesankalp** [comment]
> @codesankalp I think submission() under urls.js file should return `${urlBaseFrontend()}submissions` and not `${urlBaseFrontend()}submission`. What say?

Yes, I was thinking the same @Rahulm2310 .

File: src/components/Menubar.js (hunk 3 above)
Comment (Rahulm2310) [reply src/components/Menubar.js]: @jeeva2812 Can you please elaborate why will it not work as I applied those changes locally and it s working as expected.

Comment (jeeva2812) [reply src/components/Menubar.js]: My bad. It works. I have made the required changes. It should work fine after making the necessary changes in the backend.

**Comment by Rahulm2310** [comment]
@jeeva2812  `submission()` in `urls.js` file should return `${urlBaseFrontend()}submissions` and not `${urlBaseFrontend()}submission`. The existing changes would not work till this is applied.

**Comment by jeeva2812** [comment]
Ok. I will change that. I thought it was a part of the backend repo.
Update: Done @Rahulm2310

**Review by Rahulm2310 — APPROVED** [review]
Awesome 🎉

**Comment by Rahulm2310** [comment]
@jeeva2812 Could you please add a GIF of the fix under the `How this has been tested` section so that it is easy for reviewers to know what this PR is fixing. Thanks

**Comment by jeeva2812** [comment]
Sure. I have updated the description of the PR. @codesankalp  @Rahulm2310

**Review by codesankalp — APPROVED** [review]
Tested Locally @jeeva2812 .
It's working on reloading.
Thanks for your contribution :tada:
Tagging @isabelcosta for final review.
