### PR TITLE
Fix: Fixed the password regex with special chars

### LINKED ISSUE #38: Special characters missing from Password Regex
### Describe the bug
Currently, a few special characters are not covered in the password Regex.

### To Reproduce
1. Go to 'register user'
2. Enter a password having characters '.', '()', etc
3. Press **Register**
4. See password error still shown

### Expected behavior
All the special characters should be acceptable

### Screenshots
N/A

### Additional context
Solve this by adding support for these characters in the Regex.

### PR DESCRIPTION
**Pull request by saideepesh000**
### Description
This PR fixes the password regex to accept all special characters.

Fixes #38

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bugfix (non-breaking change which fixes an issue)

### How Has This Been Tested?
I tested this using the local repo and regex101.com

### Checklist:

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by bismitaguha — DISMISSED** [review]
LGTM

File: src/components/Register.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ class Register extends Component {
             error: null,
             submitted: false,
             emailregexp: /\S+@\S+\.\S+/,
-            passwordregexp: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{12,}$/
+            passwordregexp: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[-~`!@#$%^&*()_+=><,.|?/\\{}\[\]"':;])[A-Za-z\d-~`!@#$%^&*()_+=><,.|?/\\{}\[\]"':;]{12,}$/
```
Comment (abha224) [inline src/components/Register.js]: @saideepesh000 Can you modify the min characters required from 12 to 8 as well?

**Review by sidvenu — APPROVED** [review]
Looks good to me!

**Review by abha224 — APPROVED** [review]
